pipeline:
  build:
    image: golang
    environment:
      - GOPATH=/drone
    commands:
      - sleep 10
      - go get
      - go build
      - go test
  test:
    image: golang
    environment:
      - GOPATH=/drone
    commands:
      - sleep 5
      - go get
      - go build
      - go test